#!/bin/bash

app=Main

classpath="-cp .:../../Libs/automaton-1.11-8.jar:../../Libs/commons-lang3-3.5.jar:../../Libs/generex-1.0.2.jar:../../Libs/javafaker-1.0.2.jar:../../Libs/snakeyaml-1.23-android.jar"

function compile {
	javac $classpath $app.java
}

function run {
	java $classpath $app
}

function main {
	compile
	run
	rm -f */*.class *.class
}

main
