#!/bin/bash

app=$1

jars=.:../../Resources/automaton-1.11-8.jar:../../Resources/commons-lang3-3.5.jar:../../Resources/generex-1.0.2.jar:../../Resources/javafaker-1.0.2.jar:../../Resources/snakeyaml-1.23-android.jar

function compile {
	javac -classpath $jars $app.java
}

function run {
	java -cp $jars $app
}

function main {
	compile
	run
	rm -f */*.class *.class
}

main
